### ISSUE TITLE
Document Config file

### ISSUE THREAD

**Issue by CleanerOrc** [SBPrime/BlocksHub#17]
Could you please add some documentation on the following on the wiki or home site.  could you put a link on this github home page to the plugin home page?

Can you put some documentation on the home page on how to use the config settings, and also to describe how the BlocksHub-WorldGuard plugin operates.  

By the way, how does BlocksHub protect blocks, ie, can you only modify blocks in WG regions that you own?  What if you want to generally allow building, but only want to use worldguard to protect regions a player owns.

AsyncWorldEdit says it supports BlocksHub.  Does BlocksHub limit WorldEdit to only the blocks that it allows users to edit?

Thanks - CO.

**Comment by SBPrime** [comment]
Regarding the config I assumed that its self explanatory. I'll add a small paragraph regarding the configuration in the wiki.

"describe how the BlocksHub-WorldGuard plugin operates.", what do you have in mind? All BlocksHub-* plugins are simple bridge plugins that connect BlocksHub to the other plugin (in your example to WorldGuard).

BlocksHub is only a library that other plugins might use to access multiple block access controllers and block loggers with a unified API. It allows the plugin to log a block change (from -> to) and check if the a player is allowed to place a block in a location. So if WG will block a certain block place it should be blocked by BlocksHub. Actually BlocksHub does not block any block changes it only informs the plugin that it can't place blocks.

**Comment by CleanerOrc** [comment]
Dude, thanks for your response!

I actually never tried giving a non admin WorldEdit.  I Just tried it tho (without BlocksHub), and I’m shocked that it allows you to change blocks using WorldEdit in protected WorldGuard regions..   Seems like they should co–operate….

OK, then I added BlocksHub 1.2.jar & BlocksHub-WorldGuard 1.2.jar to the server with the correct couple of worlds in the config and tried again.  No change.  The non admin WE user can still change blocks in a protected region using WorldEdit.  What should happen?

Anyway, I guess since I don’t know really how BlocksHub is supposed to work, I can’t tell whether it’s doing its thing right or whether I have some perms set wrong…  I use it with AsyncWorldEdit and WorldEdit/WorldGuard 6 on Spigot 1.8.8   You said BlocksHub, through the access interface, tells cooperating plugins which blocks it can’t edit.   How does this work with WorldGuard regions?    Do I likely have perms setup wrong since my test user (a non–admin but with WorldEdit perms)  is able to break blocks outside of a protected region, and it can’t break them in the region.  BUT it CAN change the blocks in the protected region using WorldEdit.

Anyway, background is I was looking for some way to only allow WorldEdit in regions a person owns (except for ops, etc.)  I was initially hoping I could figure out what your plugin could do for me without going to the trouble of loading it and experimenting to find out exactly what it did.  I Tried WorldEditRegions, but had some issues and not sure it’s being maintained.   I hoped maybe your plugin file with the BlocksHub–WorldGuard plugin would let me specify which users could use WorldEdit in which regions or something…

As far as documenting the BH config, Once I saw it,  I could assume that the first couple worlds in the list enabled BlocksHub on those worlds.   But I couldn’t figure out what the “world.*” entry does.   To my mind, there were several possibilities.  Since it uses a period *, It almost looks like a perm node, so I thought maybe it causes BlocksHub to block any activity for someone with that perm node.  Or, I thought maybe it enables protection on any world whose name starts with the string “world”…      My world name is freedom, so I added – freedom and – freedom.* to the config.

Dude, I’ve been a developer for 35 years.  When you write a program everything appears “self explanatory” to you.  Trust me.  I’ve learned the hard way.  It’s a shame that it takes a while to document things, but it does reduce questions, and if you’ve documented it well enough, you can be a good guy even by saying “RTFM” (grin).


–        CO


Ryan Hamshire<https://hub.spigotmc.org/jira/secure/ViewProfile.jspa?name=BigScary> (Spigot JIRA):
“We can't code users to RTFM, but we can code our software so they don't need it. If you wait for users to get smarter and make fewer mistakes, you'll be waiting indefinitely (and, repeatedly answering the questions and complaints that stem from their mistakes). It's easier just to code around human error.”

**Comment by SBPrime** [comment]
I'll start from the end.

Since you say that you are developer for 35years you should know the saying: "the code is the documentation" and if you simply look at the code (its well organized and you can find what you are looking for quickly) you would find what you are looking for. It would take less then a minute to see what does that config entry mean (https://github.com/SBPrime/BlocksHub/blob/master/BlocksHub/src/org/PrimeSoft/blocksHub/configuration/ConfigProvider.java#L75-L91)

Now back to the subject of the config: each entry in the worlds section defines a regexp to match the world and it has nothing to do with the permission nodes.

"I guess since I don’t know really how BlocksHub is supposed to work..." I'll quote the plugin description:
"BlocksHub is a Logger & Block access API for world editing plugins. It provides a uniform way to access many block logger plugins and a simple way to check permissions to place a block.". It does not interfere with the block changing operations it only tells if that operation is permitted or not.

Regarding your setup. You set up BlocksHub correctly but you probably did not enable BlocksHub integration in AWE (check AWE configuration). BlocksHub + AWE should enable you to do what you are trying to achieve.

**Comment by CleanerOrc** [comment]
Dude, you got it right on having to change the AWE config to hookup with BlocksHub.  Thanks.

Look, I’m sorry if I was rude in my comments.  Didn’t intend to.  I was mostly frustrated and just wanted to give you a strong suggestion that might be helpful to many others including me.

Regarding your comment about “the code is the documentation”:

I doubt most guys who want to use BH are plugin developers.  I Suspect they’re just guys who have picked up some smarts on loading plugins and setting up servers.   They just want to know how your plugin works so they can get on to using it and fixing the perms so everything works ok so griefers don’t destroy their server.   But look, even if you’re a java developer (which I’m not – VB.NET & C#), you need some time to figure out the plugin code flow and how the library routines work together, etc. If I had to do that for every plugin, it’s take so long maybe I’d just only use essentials.

But my point is it only takes a few minutes to mention somewhere that the world entries in your config file are regexp.  (thanks again for the config file update on this!)

Yeah, I could do it, but it would take me a while to find the right place in the code…  I’m not a github user either (though I am slowly trying to pick it and java up… )  And look Dude, I’d tell this to my own brother – I’m sorry, but It’s just not obvious that “world.*” is a regexp, (especially when so many perm nodes are formatted like that).

Besides though, we’re just talking about documenting some of BH’s basic operations that aren’t likely to change since they’re basic to BH’s operation.

Dude, what about considering a Configuration section on your page that mentions that the worlds entries are regexp, and a reminder to configure AWE for BlocksHub for those newbies who haven’t used it yet.  Me, I’ve used it for maybe 6 months,  but I didn’t remember that you have to enable BlocksHub, since I originally went with WorldEditRegions which uses perm nodes to control things.

Anyway, on your statement:

about your comment , "I guess since I don’t know really how BlocksHub is supposed to work..." I'll quote the plugin description:  "BlocksHub is a Logger & Block access API for world editing plugins. It provides a uniform way to access many block logger plugins and a simple way to check permissions to place a block.". It does not interfere with the block changing operations it only tells if that operation is permitted or not.
Dude, your statement “It provides a uniform way to access many block logger plugins and a simple way to check permissions to place a block” is hard to decipher.  For you the programmer – maybe not so much because you know intimately how things are hooked up.  But for the non–programmer or newbie (and me), it sounds like you can use perm nodes.  I think what you mean is that “it provides a uniform way to limit WorldEdit operations to only the  blocks that your access plugins allow access to” or some such.

FWIW, If it were me, I’d also take the high ground of adding the obvious, that WorldEdit operations don’t natively honor any block protection, but if your use AWE, it’s compatible with BlocksHub, which will work with your Logger and Access plugin of choice to limit WorldEdit operations to only blocks users have access to.

Dude, thanks for the discussion and your help!

Mark (CO)

**Comment by SBPrime** [comment]
I pointed out the piece of the code because you said that you are a software developper. If i don't know how a certain program/plugin works and I cant find the documentation I always check the code, and most of my friends do the same. I realize that it takes time but you can see how other ppl tend to do things and you might use that in your future projects. I realize that most server "admins" (" is intentional because I would not call some of those ppl admins) don't have a clue how plugins and developement works. Therefore it might be impossible and misleading for them how the worlds are configurated without documentation. That's the reason why I agreed that the config information would be nice.

As I stated I'm going to add a config section on the wiki as soon as I find time. You might know or not (depends If you are a spigot user or not) that I have much more projects and BH is a side small project. In addition to that most of my open source projects are in maintenance mode. I'll do it when I have time and then I'll close this issue nothing less nothing more.

I provided you with the saying: "the code is the documentation" because this is what I received when I asked for documentation for several open source projects and in addition to that, like you noticed, your answer was on the rude side. Don't get me wrong I have nothing against constructive critics but I don't like when the critics gets personal. I always try to help everyone that contacts me and asks for help.

Regarding the plugin description ("BlocksHub is a Logger & Block access API for world editing plugins...."), this phrase is a paraphrase of the vault description. The "API" might not mean much to a simple user but to a software developper it means more then 100 words. Therefore you might call this plugin a "library plugin" that ppl should install if any other plugin requests it (similar to vault) and don't care how it works and not over think it.

Regarding the AWE configuration. In my opinion this is not the place to inform ppl how to set up AWE to use this plugin properly (I don't even provide a list of plugins that use BH!). All the necessary information is provided on the AWE configuration page. In addition to that AWE is not the only plugin that uses BH.

**Comment by SBPrime** [comment]
Config information added, closing the issue. If you still want to continue the discussion please feel free to do so.

**Comment by CleanerOrc** [comment]
SBPrime, thanks much!
